name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          echo "TAG=${{ secrets.DOCKERHUB_USERNAME }}/mywhisper:latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAG }}